version: "3.8"
services:
  krx-bot:
    build: .
    container_name: krx-bot
    restart: unless-stopped
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      LOG_LEVEL: WARNING
